# This is a basic workflow to help you get started with Actions

name: Part 2

# Controls when the action will run. 
on: [push]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run part 2 test files
      - run: gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 ./part2/crash1.gft
      - run: gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 ./part2/crash2.gft
      - run: gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 ./part2/hang.gft
